### ISSUE TITLE
【交易确认】界面，显示信息不对：输入的要发送1.1ELA，1. 显示的发送金额 = 实际发送金额/1000000（小米手机）；2. 手续费显示不对，显示为0；3.总花费也显示不对，和显示的要发送金额一致；

### ISSUE THREAD

**Issue by xuliting** [elastos/Elastos.App.Wallet.Elephant.Android#10]
备注：
（在此之前写0.2也发送出去过，突然就变这样了）
![wechatimg151](https://user-images.githubusercontent.com/18321471/47909308-7b686780-deca-11e8-80cb-c45dbd76c818.jpeg)

**Comment by xidaokun** [comment]
git：fix bug #10

**Comment by xuliting** [comment]
手续费的显示和计算在另一个issue中有体现；
其他验证通过；
