### ISSUE TITLE
中、英文【指纹授权支出限额】界面：下方的选项不见了。（同时关注 面部授权支出限额界面是否存在）

### ISSUE THREAD

**Issue by xuliting** [elastos/Elastos.App.Wallet.Elephant.Android#114]
![image](https://user-images.githubusercontent.com/18321471/50340100-89467a80-0554-11e9-9773-54fc10ff35f4.png)

**Comment by xidaokun** [comment]
fixed

**Comment by xuliting** [comment]
指纹授权界面测试验证通过 ；
面部授权界面暂时未找到安卓手机在这个应用中支持面部授权。
