### ISSUE TITLE
ethereum not showing

### ISSUE THREAD

**Issue by blueprintjonny** [elastos/Elastos.App.Wallet.Elephant.Android#130]
downloaded the wallet to try and love the interface etc. I sent over some BTC and it arrived really quickly. I then sent over an Ethereum and BGX Tokens and they have not arrived in my wallet. its been many hours now and still no sign. i checked the transaction on etherscan and it has been completed with hundreds of confirmations but still no sign in my wallet. I have noticed when i open the wallet the only coin to synchronize is BTC all the others do not sync. Any ideas?
![screenshot_20181230-100545](https://user-images.githubusercontent.com/46258629/50546166-2cfded80-0c1b-11e9-87d4-bd4228c58c1d.jpg)
![screenshot_20181230-100608_gmail](https://user-images.githubusercontent.com/46258629/50546167-2cfded80-0c1b-11e9-87a2-f814d86d5550.jpg)
![screenshot_20181230-100634_samsung internet](https://user-images.githubusercontent.com/46258629/50546168-2d968400-0c1b-11e9-82aa-46a09c887396.jpg)

**Comment by Griff233** [comment]
Have had similar issues with ETH, can see the transaction has been confirmed, the wallet will show the balance for a while, then it will vanish, only to return a few seconds later.
For some reason, running the sync in BTC seems to have made it a little more stable.

**Comment by blueprintjonny** [comment]
Mine never arrived at all. Wallet shows zero and has never shown anything else!

**Comment by blueprintjonny** [comment]
Yeah I had a similar thing with all the Chinese writing. Ended up updating though and I'm running version 1.0.22 build 22

**Comment by Griff233** [comment]
Ok ditto same build, 
I'm all out of ideas, do you know how to raise an official bug report?
Please keep me posted of your progress.

**Comment by blueprintjonny** [comment]
I don't unfortunately. I've raised this issue. If I was to uninstall the app and reinstall then input my secret words I would still have my btc funds right? Plus hopefully the missing ethereum. I will keep you posted. thank you for helping

**Comment by Griff233** [comment]
If you have an old phone about, you could test it on that first.

**Comment by Griff233** [comment]
just wanted to let you know that a new build has been released 1.0.23

**Comment by xuliting** [comment]
Yesterday we sent a version to solve the ETH display problem, please upgrade the wallet and check if it is resolved.

**Comment by blueprintjonny** [comment]
Thank you. I've upgraded and the issue has indeed been resolved. Really great app, thanks very much :)

**Comment by xuliting** [comment]
I am very glad to hear that your problem has been solved. Thank you for your attention and support.
