### ISSUE TITLE
【发送交易---申请金额】进入ELA交易界面，点击 接收--申请金额，选择以CNY单位，输入数字，1. 扫描出的数据有误；2.当扫描出的数额超过余额时，显示的中文提示信息中，存在英文； 3.当扫描出的数额超过余额时，发送最大值有问题，最大值应该是当前余额（同时需要预留手续费）；

### ISSUE THREAD

**Issue by xuliting** [elastos/Elastos.App.Wallet.Elephant.Android#36]
进入ELA交易界面，点击 接收--申请金额，选择以CNY单位，输入数字；用另一手机进入交易-发送-扫描；
期望结果：
扫描出的数目正确（包含申请金额和手续费）；
实际结果：
1.扫描出的数字不正确
   0.1 CNY, 扫描出4ELA；0.2CNY，扫描出7ELA
2.当扫描出的数额超过余额时，显示的中文提示信息中，存在英文；
3.当扫描出的数额超过余额时，发送最大值有问题，最大值应该是当前余额（同时需要预留手续费）；
![1651542274785_ pic_hd](https://user-images.githubusercontent.com/18321471/48544038-bff9f700-e8fd-11e8-985c-ed30d2c6de79.jpg)
![1661542274793_ pic_hd](https://user-images.githubusercontent.com/18321471/48544132-f33c8600-e8fd-11e8-9abf-59abd2ebb531.jpg)

**Comment by xidaokun** [comment]
commit fix bug#31

**Comment by xuliting** [comment]
目前只解决了问题1。

**Comment by xuliting** [comment]
目前扫描带申请金额的二维码后，进入金额输入页面。改成这个流程后，该问题不再出现。现关闭该问题。
